mp.jwt.verify.issuer = jwt-issuer
mp.jwt.verify.publickey.location = ../jwt/publicKey.pem

quarkus.http.port = 8090

# Container image build disabled - using AWS Lambda deployment instead
# quarkus.container-image.build = true
# quarkus.container-image.group = onyx-softworks
# quarkus.container-image.name = onyx

quarkus.datasource.db-kind = mariadb
%prod.quarkus.datasource.username = root
%prod.quarkus.datasource.password = s3cr3t
%prod.quarkus.datasource.jdbc.url = jdbc:mariadb://localhost:3306/onyx

quarkus.hibernate-orm.database.generation.create-schemas = true

%test.quarkus.hibernate-orm.database.generation = drop-and-create
%test.quarkus.hibernate-orm.sql-load-script = db/test-data.sql

%prod.quarkus.hibernate-orm.scripts.generation = drop-and-create
%prod.quarkus.hibernate-orm.scripts.generation.create-target = db/create.sql
%prod.quarkus.hibernate-orm.scripts.generation.drop-target = db/drop.sql
%prod.quarkus.hibernate-orm.sql-load-script = db/import.sql

quarkus.swagger-ui.always-include = true

# Onyx-Related
onyx.support-email = support@onyx-softworks.com

# Payouts Properties for CyberSource
cybersource.merchant.reference-number = 4200121
cybersource.merchant.funds-source = 05
cybersource.merchant.business-application = PP
cybersource.merchant.name = Onyx Softworks
cybersource.merchant.city = Bridgetown
cybersource.merchant.country-code = BB
cybersource.merchant.currency = BBD

# Properties for CyberSource; Flex Microform
merchantId = testrest
keyId = 
sharedSecret = 
authenticationType = http_signature
runEnvironment = apitest.cybersource.com
requestJsonPath = src/main/resources/request.json