simplejavamail.javaxmail.debug=true
simplejavamail.transportstrategy=SMTPS
simplejavamail.smtp.host=smtp.gmail.com
simplejavamail.smtp.port=25
simplejavamail.smtp.username=username
simplejavamail.smtp.password=password

simplejavamail.defaults.from.name=Onyx Softworks
simplejavamail.defaults.from.address=donotreplay@onyx-softworks.com
simplejavamail.defaults.replyto.name=Do-Not-Reply
simplejavamail.defaults.replyto.address=donotreplay@onyx-softworks.com
simplejavamail.defaults.bcc.name=Email Logs
simplejavamail.defaults.bcc.address=emaillogs@onyx-software.com
simplejavamail.defaults.trustallhosts=false